# Generated by Django 5.2.4 on 2025-10-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Repuesto')),
                ('marca_auto', models.CharField(max_length=100, verbose_name='Marca del Auto Compatible')),
                ('modelo_auto', models.CharField(blank=True, max_length=100, verbose_name='Modelo Compatible')),
                ('año_desde', models.IntegerField(blank=True, null=True, verbose_name='Año Desde')),
                ('año_hasta', models.IntegerField(blank=True, null=True, verbose_name='Año Hasta')),
                ('categoria', models.CharField(choices=[('motor', 'Motor'), ('transmision', 'Transmisión'), ('suspension', 'Suspensión'), ('frenos', 'Frenos'), ('electrico', 'Sistema Eléctrico'), ('carroceria', 'Carrocería'), ('interior', 'Interior'), ('otros', 'Otros')], max_length=50, verbose_name='Categoría')),
                ('descripcion', models.TextField(verbose_name='Descripción del Repuesto')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado_excelente', 'Usado - Excelente'), ('usado_bueno', 'Usado - Bueno'), ('usado_regular', 'Usado - Regular')], max_length=30, verbose_name='Estado')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('nombre_vendedor', models.CharField(max_length=200, verbose_name='Nombre del Vendedor')),
                ('email_vendedor', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono_vendedor', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('disponible', models.BooleanField(default=True)),
                ('vistas', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Publicación de Venta',
                'verbose_name_plural': 'Publicaciones de Venta',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_auto', models.CharField(max_length=100, verbose_name='Marca del Auto')),
                ('modelo_auto', models.CharField(blank=True, max_length=100, verbose_name='Modelo del Auto')),
                ('año_auto', models.IntegerField(blank=True, null=True, verbose_name='Año del Auto')),
                ('categoria_repuesto', models.CharField(choices=[('motor', 'Motor'), ('transmision', 'Transmisión'), ('suspension', 'Suspensión'), ('frenos', 'Frenos'), ('electrico', 'Sistema Eléctrico'), ('carroceria', 'Carrocería'), ('interior', 'Interior'), ('otros', 'Otros')], max_length=50, verbose_name='Categoría del Repuesto')),
                ('repuesto_especifico', models.CharField(max_length=200, verbose_name='Repuesto Específico')),
                ('descripcion_adicional', models.TextField(blank=True, verbose_name='Descripción Adicional')),
                ('urgencia', models.CharField(choices=[('baja', 'Baja - Puedo esperar'), ('media', 'Media - Lo necesito pronto'), ('alta', 'Alta - Urgente')], max_length=20, verbose_name='Nivel de Urgencia')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('dni', models.CharField(max_length=20, verbose_name='DNI')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Compra',
                'verbose_name_plural': 'Solicitudes de Compra',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
