# Generated by Django 5.2.4 on 2025-11-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='telefono',
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='celular',
            field=models.CharField(default='', max_length=20, verbose_name='Celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='localidad',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='nombre',
            field=models.CharField(default='', max_length=200, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='nro_chasis',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='VIN/Número de Chasis'),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='zona',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Zona/Provincia'),
        ),
        migrations.AlterField(
            model_name='solicitudcompra',
            name='urgencia',
            field=models.CharField(choices=[('baja', 'Baja - Puedo esperar'), ('media', 'Media - Lo necesito pronto'), ('alta', 'Alta - Urgente'), ('super_alta', 'Super Alta - Muy Urgente (en hora)')], max_length=20, verbose_name='Nivel de Urgencia'),
        ),
    ]
