# Generated by Django 5.2.4 on 2025-11-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_publicacionventa_localidad_publicacionventa_zona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacionventa',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='publicacionventa',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='publicacionventa',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud'),
        ),
    ]
