# Generated by Django 5.2.4 on 2025-11-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_publicacionventa_direccion_publicacionventa_latitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacionventa',
            name='año_desde',
        ),
        migrations.RemoveField(
            model_name='publicacionventa',
            name='año_hasta',
        ),
        migrations.RemoveField(
            model_name='publicacionventa',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='publicacionventa',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='publicacionventa',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='publicacionventa',
            name='marca_auto',
        ),
        migrations.RemoveField(
            model_name='publicacionventa',
            name='modelo_auto',
        ),
        migrations.RemoveField(
            model_name='publicacionventa',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='publicacionventa',
            name='titulo',
        ),
    ]
