# Generated by Django 5.2.7 on 2025-11-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_publicacionventa_direccion_publicacionventa_latitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='email',
        ),
    ]
