# Generated by Django 5.2.7 on 2025-11-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_publicacionventa_año_desde_and_more'),
        ('core', '0005_remove_solicitudcompra_email'),
    ]

    operations = [
    ]
