# Generated by Django 5.2.4 on 2025-11-26 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20251111_1152'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcompra',
            name='foto_repuesto',
            field=models.ImageField(blank=True, null=True, upload_to='repuestos_fotos/', verbose_name='Foto del Repuesto'),
        ),
        migrations.AlterField(
            model_name='solicitudcompra',
            name='celular',
            field=models.CharField(default='', max_length=20, verbose_name='Celular'),
        ),
        migrations.CreateModel(
            name='VendedorEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('cuit', models.CharField(max_length=13, unique=True, verbose_name='CUIT')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('localidad', models.CharField(max_length=200, verbose_name='Localidad')),
                ('provincia', models.CharField(max_length=200, verbose_name='Provincia')),
                ('web_ig', models.CharField(blank=True, max_length=200, verbose_name='Web/Instagram')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendedor Empresa',
                'verbose_name_plural': 'Vendedores Empresas',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('enviada', 'Enviada al cliente'), ('rechazada', 'Rechazada'), ('cliente_interesado', 'Cliente interesado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='core.solicitudcompra')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='core.vendedorempresa')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('solicitud', 'vendedor')},
            },
        ),
    ]
