# Generated by Django 5.2.4 on 2025-12-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_solicitudcompra_foto_repuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedorempresa',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='vendedorempresa',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud'),
        ),
    ]
