# Generated by Django 5.2.4 on 2025-12-04 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_vendedorempresa_latitud_vendedorempresa_longitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='foto_repuesto',
        ),
        migrations.CreateModel(
            name='ImagenRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='repuestos_fotos/', verbose_name='Imagen del Repuesto')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.solicitudcompra')),
            ],
            options={
                'verbose_name': 'Imagen de Repuesto',
                'verbose_name_plural': 'Imágenes de Repuestos',
                'ordering': ['fecha_subida'],
            },
        ),
    ]
