# Generated by Django 5.2.4 on 2025-11-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_solicitudcompra_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacionventa',
            name='localidad',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='publicacionventa',
            name='zona',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Zona/Provincia'),
        ),
        migrations.AlterField(
            model_name='publicacionventa',
            name='ubicacion',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Ubicación'),
        ),
    ]
