# Generated by Django 5.2.4 on 2025-11-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiero_comprar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='email',
        ),
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='telefono',
        ),
        migrations.AddField(
            model_name='publicacionventa',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='publicacionventa',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='publicacionventa',
            name='localidad',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='publicacionventa',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='publicacionventa',
            name='zona',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Zona/Provincia'),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='celular',
            field=models.CharField(default='', max_length=20, verbose_name='Celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='localidad',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='nombre',
            field=models.CharField(default='', max_length=200, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='nro_chasis',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='VIN/Número de Chasis'),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='zona',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Zona/Provincia'),
        ),
        migrations.AlterField(
            model_name='publicacionventa',
            name='ubicacion',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='solicitudcompra',
            name='urgencia',
            field=models.CharField(choices=[('baja', 'Baja - Puedo esperar'), ('media', 'Media - Lo necesito pronto'), ('alta', 'Alta - Urgente'), ('super_alta', 'Super Alta - Muy Urgente')], max_length=20, verbose_name='Nivel de Urgencia'),
        ),
    ]
